### ISSUE TITLE
The branch name of the tree is the same as the name of the template function

### ISSUE THREAD

**Issue by wanxn518** [TongZhou2017/itol.toolkit#35]
Hello great developers, this tool is very helpful for our research and I am learning how to use it proficiently.

I found that the branch names of the tree in the sample data provided were the same as the names of the template functions, which led to confusion when I tried using the sample data, and this is from a novice using itol and itol.toolkit

Best!
XiaoNan

**Comment by TongZhou2017** [comment]
Dear Xiaonan,

Thank you for your affirmation and use of itol.toolkit. We are glad that itol.toolkit has been helpful for your research. We fully understand the confusion faced by beginners when using itol and itol.toolkit. We will continue to optimize the tool and related tutorials to lower the learning threshold and allow more researchers to quickly master and efficiently use them.

The confusion caused by sample data branch names being the same as template function names, we will improve this in subsequent updates and add richer sample data with different branch names rather than using template names. We provide some examples of different branch names in the [gallery](https://tongzhou2017.github.io/itol.toolkit-gallery/), which may be the fastest way to view the relevant code. If you are not very familiar with itol and other basics, we are also producing related basic courses, and these resources will gradually become public.

If you have specific questions that you need our help with, you are welcome to communicate with us on the issue page. This will help us further improve itol.toolkit. We also have active user communities on platforms such as WeChat, Discord, and Slack. If you want to join our WeChat user group, you can add me: zitangumu.

Once again, thank you for your valuable opinions and suggestions. We will continue to work hard to improve the usability of the tools and related resources to help more researchers efficiently use itol and itol.toolkit. We look forward to more in-depth communication with you!

Sincerely,
Tong

**Comment by wanxn518** [comment]
Dear Tong

Thank you for your enthusiastic reply！

I have successfully used some single functions which are very fast and easy for my work, I have a small question, for the function DATASET_COLORSTRIP, will the legend about the color bars be generated automatically?

Best,
Xiaonan

**Comment by TongZhou2017** [comment]
Hi Xiaonan,

Please see [issue#34](https://github.com/TongZhou2017/itol.toolkit/issues/34#issue-1730740491)

Tong
