### ISSUE TITLE
Problems encountered during operation

### ISSUE THREAD

**Issue by wanxn518** [TongZhou2017/itol.toolkit#38]
Hi Dr. Zhou
![image](https://github.com/TongZhou2017/itol.toolkit/assets/97587984/bf56bb51-b5aa-48f4-b40c-5518fe3f1612)
Thank you very much for the great tool you have developed, I am running with this error and I don't know what to do, can you give me some good advice?

**Comment by TongZhou2017** [comment]
Dear wanxn518,

Thank you for using itol.toolkit. Based on the commands, I suspect the issue may be due to the column for setting color being larger than 75.

If possible, could you share an example dataset with me? I would be happy to test it out to identify the root cause.
Please let me know if you have any other questions. I appreciate you taking the time to report this issue, as it will help improve itol.toolkit for all users.

Best regards,
Tong

**Comment by wanxn518** [comment]
Hi Dr. Zhou

Thank you very much for your reply, I have provided the data file in the attachment.
[test_tree.zip](https://github.com/TongZhou2017/itol.toolkit/files/13235969/test_tree.zip)

Best,
wanxn

**Comment by TongZhou2017** [comment]
I reviewed the code in the zip file provided. It only demonstrates template generation for tree coloring, but does not include implementation of the tree collapse method. You can refer to this link for examples of how to implement tree collapsing in ITOL: https://tongzhou2017.github.io/itol.toolkit/articles/COLLAPSE.html.

I also checked the tree tip IDs in your code. The format used is GB_GCA_013538855.1. However, I did not find any IDs matching this format in the tree screenshot you shared. Please verify that the tip IDs you are using in the code match the correct format of the IDs shown in your phylogenetic tree. Using mismatched IDs between the code and tree data can lead to errors.
