### ISSUE TITLE
The single column input problem 

### ISSUE THREAD

**Issue by yuxiangtan** [TongZhou2017/itol.toolkit#42]
**Describe the bug**
> unit_2 <- create_unit(data = meta_df %>% select(tips_ID, log2_genome),
                      key = "GTDB unssaigned LV",
                      type = "DATASET_GRADIENT",
                      tree = tree_f)
Using the first column as id: tips_ID
Error in UseMethod("tbl_vars") :
  no applicable method for 'tbl_vars' applied to an object of class "c('double', 'numeric')"

I solve this problem by:
> library(tibble)
> unit_1 <- create_unit(data = meta_df %>% select(tips_ID, log2_genome)%>% as.tibble(),
                      key = "log2 genome_number",
                      type = "DATASET_GRADIENT",
                      tree = tree_f)
Using the first column as id: tips_ID
Warning message:
`as.tibble()` was deprecated in tibble 2.0.0.
ℹ Please use `as_tibble()` instead.
ℹ The signature and semantics have changed, see `?as_tibble`.
This warning is displayed once every 8 hours.
Call `lifecycle::last_lifecycle_warnings()` to see where this warning was generated.

**Additional context**
This tool is very useful, but this bug is very confusing.

Best,

**Comment by TongZhou2017** [comment]
I guess the meta_df object is a data.frame, if use data.table::fread will solve this problem. The tibble is a better format than data.frame in this case because they don't have row names. The first column is used for arching as id to link metadata.

If there is any possibility, please share the example data. I will try to improve the programming details.
